### ISSUE TITLE
Keybinding conflict on Mac OS X

### ISSUE THREAD

**Issue by ebelew** [sblask/firefox-image-forward#3]
The default binding of Meta-Space is the canonical keyboard shortcut for Spotlight Search in OS X.  

While I can (and did) rebind the buttons using the shortcut editor, the default should really pick a different key when on a Mac OS X system. I changed it to Alt-Space and Alt-shift-Space since they were free. I know that these buttons are taken on Windows, but I'm pretty sure you can just select the modifier based on platform when setting the defaults.

**Comment by Aelius-Saionji** [comment]
You could look at the useragent to grab the current OS. Make a note that you have done this, so that people changing their UA will know what to expect.

While we're on the subject, why not just make the keybindings configurable by an about:config setting? I don't really like the idea of installing another extension just to modify the shortcuts of one other extension.

**Comment by sblask** [comment]
Not sure I have access on the user agent from the plugin code, especially with the changes that are to come with e10s. You can change all keyboard shortcuts with that extension (https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/) including the ones from other extensions unless they didn't follow the standard way of doing it. I don't want to invent my own way of handling keyboard shortcuts either...

**Comment by Link-Satonaka** [comment]
The problem seems to be with another extension but it will take me more time to figure out which one. Here is what it I see for the default keybindings (in a fresh profile and my current profile, it is no different).
![clipboard01](https://cloud.githubusercontent.com/assets/4342746/5688574/de3c9d8e-9826-11e4-8743-659aedc82a47.png)

When I change the keybindings in my old profile, imageforward responds to both the new and old keybindings, and ctrl-shift-anykey are swallowed.
In a new profile, ctrl-shift-b is always caught by firefox and opens the bookmarks, so the default of ctrl-shift-b does not work and should be changed.

I'm too lazy to get to the bottom of this- the problem appears to just be within my browser profile and Pentadactyl is allowing me to bludgeon everything into line. When I map Ctrl-Shift-A to Tools.Add-ons via pentadactyl, it overrides everything else and works. Pentadactyl will also allow me to map the javascript functions you've provided to a keyboard shortcut.

**Comment by Link-Satonaka** [comment]
This might be useful for the UA- this is meant to be a pentadactyl plugin. There are extensions for firefox to handle the UA, I'm sure it can be read.

http://sprunge.us/ZAKI
