### ISSUE TITLE
Default keybinding conflicts with firefox internal keybinding.

### ISSUE THREAD

**Issue by Link-Satonaka** [sblask/firefox-image-forward#4]
Ctrl-Shift-B is how you get to firefox's bookmarks.

**Comment by sblask** [comment]
I was just looking into keybinding as I migrate to the webextension API, isn't Ctrl-Shift-O the shortcut? It definitely is under Linux. Nothing to be found here: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by Link-Satonaka** [comment]
Look a little closer :P 

`Library window (Bookmarks)`
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_bookmarks

**Comment by sblask** [comment]
Now isn't that clever, the shortcuts for Windows aren't visible unless I change my user agent. And no indication that there is a difference between operating systems or the ability to switch on the page...

**Comment by Link-Satonaka** [comment]
Huh, I went out of my way to change my user agent because I thought this might be the case. For some reason I always saw ctrl shift b, though.

**Comment by sblask** [comment]
Maybe your add-on is broken? I used https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher-revived/ When choosing Mac or Linux I get `Ctrl-Shift-O` and only under Windows I get `Ctrl-Shift-B` as the shortcut. Anyway, it's simple enough to change it with webextensions, I just need to add a line for Windows in manifest.json. I'll have to wait with a release until Firefox 55 though because webextension keybindings with `Space` are broken and got fixed only a few days ago.
